#!/usr/bin/env python
# encoding: utf-8

"""
Here's the list of words used to search the REF case studies
"""

SEARCH_TERM_LIST = [
    'algorithm',
    'big data',
    'beautifulsoup',
    'computation',
    'computational',
    'computed',
    'computer',
    'computing',
    'data analysis',
    'data base',
    'database',
    'microsoft excel',
    'ms excel',
    'fortran',
    'geographic information science',
    'geographic information systems',
    'gis',
    'git',
    'github',
    'graphics',
    'high performance computing',
    'hpc',
    'imagej',
    'in silico',
    'matlab',
    'matplotlib',
    'modeling',
    'modelling',
    'numpy',
    'nvivo',
    'open source',
    'open-source',
    'programming language',
    'python',
    'quantitative analysis',
    'r language',
    'scrapy',
    'scipy',
    'simulated',
    'simulation',
    'software',
    'spss',
    'sqlalchemy',
    'stata',
    'statistical',
    'supercomputer',
    'supercomputing',
    'visualisation',
    'visualization',
    'Rcpp',
    'ggplot2',
    'plyr',
    'stringr',
    'reshape2',
    'RColorBrewer',
    'workflow',
    'wxpython',
    ]
